// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB4vrnmZhKgFzEoO2ogdvZmBcTbTUyGDs',
    appId: '1:496530649682:web:d1fbd2cb58ce46a592e58b',
    messagingSenderId: '496530649682',
    projectId: 'chat-app-f7f55',
    authDomain: 'chat-app-f7f55.firebaseapp.com',
    storageBucket: 'chat-app-f7f55.appspot.com',
    measurementId: 'G-ZMRJ620VMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxL7zGsfKJHGn6Vtkd7Ol6JSwEfwp1P0',
    appId: '1:496530649682:android:ad05d652b138f26c92e58b',
    messagingSenderId: '496530649682',
    projectId: 'chat-app-f7f55',
    storageBucket: 'chat-app-f7f55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOTLccHwG9PuaLPH6rpByGkVR3K7cN3Q',
    appId: '1:496530649682:ios:4be00fa8b57c836192e58b',
    messagingSenderId: '496530649682',
    projectId: 'chat-app-f7f55',
    storageBucket: 'chat-app-f7f55.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgOTLccHwG9PuaLPH6rpByGkVR3K7cN3Q',
    appId: '1:496530649682:ios:4be00fa8b57c836192e58b',
    messagingSenderId: '496530649682',
    projectId: 'chat-app-f7f55',
    storageBucket: 'chat-app-f7f55.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB4vrnmZhKgFzEoO2ogdvZmBcTbTUyGDs',
    appId: '1:496530649682:web:4798a8fe709efa1292e58b',
    messagingSenderId: '496530649682',
    projectId: 'chat-app-f7f55',
    authDomain: 'chat-app-f7f55.firebaseapp.com',
    storageBucket: 'chat-app-f7f55.appspot.com',
    measurementId: 'G-PPSCM9FRX8',
  );

}